const lang = {
  en: {
    search: "Search",
    signOut: "Sign Out",
    signIn: "Sign In",
    signUp: "Sign Up",
    signInNow: "Sign In now",
    signUpNow: "Sign Up now",
    alreadyHavingAccount: "Already having account! ",
    newToNetflix: "New to Netflix? ",
    play: "Play",
    moreInfo: "More Info",
    pleaseFillAllDetails: "Please fill all details!",
    emailIsNotValid: "Email is not valid",
    passwordIsNotValid: "Password is not valid",
    enterName: "Enter Name",
    enterEmail: "Enter email",
    enterPassword: "Enter password",
    gptSearchPlaceHolder: "What do you want to watch today?",
  },
  hi: {
    search: "खोज",
    signOut: "साइन आउट",
    signIn: "दाखिल करना",
    signUp: "साइन अप करें",
    signInNow: "अब साइन इन करो",
    signUpNow: "अभी साइनअप करें",
    alreadyHavingAccount: "पहले से ही खाता है! ",
    newToNetflix: "नेटफ्लिक्स पर नए हैं? ",
    play: "खेल",
    moreInfo: "और जानकारी",
    pleaseFillAllDetails: "कृपया सभी विवरण भरें!",
    emailIsNotValid: "विद्युतडाक मान्य नहीं है",
    passwordIsNotValid: "पासवर्ड मान्य नहीं है",
    enterName: "नाम दर्ज करें",
    enterEmail: "ईमेल दर्ज करें",
    enterPassword: "पास वर्ड दर्ज करें",
    gptSearchPlaceHolder: "आज आप क्या देखना चाहते हैं?",
  },
  telugu: {
    search: "వెతకండి",
    signOut: "సైన్ అవుట్ చేయండి",
    signIn: "సైన్ ఇన్ చేయండి",
    signUp: "చేరడం",
    signInNow: "ఇప్పుడే సైన్ ఇన్ చేయండి",
    signUpNow: "ఇప్పుడే సైన్ అప్",
    alreadyHavingAccount: "ఇప్పటికే ఖాతా ఉంది! ",
    newToNetflix: "Netflixకి కొత్తవా? ",
    play: "ఆడండి",
    moreInfo: "మరింత సమాచారం",
    pleaseFillAllDetails: "దయచేసి అన్ని వివరాలను పూరించండి!",
    emailIsNotValid: "ఇమెయిల్ చెల్లదు",
    passwordIsNotValid: "పాస్‌వర్డ్ చెల్లదు",
    enterName: "పేరు నమోదు చేయండి",
    enterEmail: "ఇమెయిల్‌ని నమోదు చేయండి",
    enterPassword: "రహస్య సంకేతం తెలపండి",
    gptSearchPlaceHolder: "ఈరోజు మీరు ఏమి చూడాలనుకుంటున్నారు?",
  },
};

export const SUPPORTED_LAUNGUAGES = [
  { identifier: "en", name: "English" },
  { identifier: "hi", name: "Hindi" },
  { identifier: "telugu", name: "Telugu" },
];

export default lang;
